// Generated by CoffeeScript 1.6.3
var config;

config = {
  ns: "auth",
  filename: __filename,
  scripts: {
    register: require("./register/index"),
    login: require("./login/index"),
    changePassword: require("./changePassword/index")
  }
};

module.exports = function(app, options) {
  return app.createLibrary(config, options);
};
